name: coverage
on:
  push:
    branches: [ master, 'dev/**' ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: actions/checkout@v6
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: mvn -B test --file pom.xml -Dcom.urbanspork.test.client.port=52081 -Dcom.urbanspork.test.server.port=52082
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{secrets.CODECOV}}
