name: release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  client:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: mvn package -B -f pom.xml
      - name: Upload client artifact
        uses: actions/upload-artifact@v7
        with:
          name: urban-spork-client-${{ runner.os }}
          path: urban-spork-client-gui/target/*.zip
          retention-days: 1
          overwrite: true
      - name: Upload native library
        uses: actions/upload-artifact@v7
        with:
          name: urban-spork-native-${{ runner.os }}
          path: urban-spork-jni/target/classes/native/
          retention-days: 1
          overwrite: true
  server:
    needs: client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: maven
      - name: Download native libraries
        uses: actions/download-artifact@v4
        with:
          pattern: urban-spork-native-*
          path: urban-spork-jni/target/classes/native/
          merge-multiple: true
      - name: Build with Maven
        run: mvn package -B -pl urban-spork-server -am
      - name: Check native library
        run: |
          cd urban-spork-server/target
          unzip -p *.zip 'urban-spork-server/lib/urban-spork-jni-*.jar' > jni.jar
          unzip -l jni.jar | grep win32-x86-64/ciphers.dll
      - name: Upload server artifact
        uses: actions/upload-artifact@v7
        with:
          name: urban-spork-server
          path: urban-spork-server/target/*.zip
          retention-days: 1
          overwrite: true
  release:
    needs: [ client, server ]
    runs-on: ubuntu-latest
    steps:
      - name: Download client artifact
        uses: actions/download-artifact@v4
        with:
          pattern: urban-spork-client-*
          path: dist
          merge-multiple: true
      - name: Download server artifact
        uses: actions/download-artifact@v4
        with:
          name: urban-spork-server
          path: dist
      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: dist/*.zip
          prerelease: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
