name: test
on: workflow_dispatch
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.ref }}
      - name: Setup rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'oracle'
          cache: maven
      - name: Test with Maven
        run: mvn test -B -f pom.xml "-Dcom.urbanspork.test.client.port=52081" "-Dcom.urbanspork.test.server.port=52082" "-Durban-spork.netty.log.level=DEBUG"
